=== cvogt/freealbion/data/dtd/config.dtd
<!ELEMENT config (#PCDATA | screen | projection | input | sleep | graphic | graphic_device | inferred | opencl | albion)*>
<!ELEMENT screen (#PCDATA)*>
<!ATTLIST screen
	width CDATA #REQUIRED
	height CDATA #REQUIRED
	fullscreen CDATA #REQUIRED
	vsync CDATA #REQUIRED
	stereo CDATA #REQUIRED
>
<!ELEMENT projection (#PCDATA)*>
<!ATTLIST projection
	fov CDATA #REQUIRED
	near CDATA #REQUIRED
	far CDATA #REQUIRED
>
<!ELEMENT input (#PCDATA)*>
<!ATTLIST input
	key_repeat CDATA #REQUIRED
	ldouble_click CDATA #REQUIRED
	mdouble_click CDATA #REQUIRED
	rdouble_click CDATA #REQUIRED
>
<!ELEMENT sleep (#PCDATA)*>
<!ATTLIST sleep
	time CDATA #REQUIRED
>
<!ELEMENT graphic (#PCDATA)*>
<!ATTLIST graphic
	filtering CDATA #REQUIRED
	anisotropic CDATA #REQUIRED
	anti_aliasing CDATA #REQUIRED
>
<!ELEMENT graphic_device (#PCDATA)*>
<!ATTLIST graphic_device
	disabled_extensions CDATA #REQUIRED
	force_device CDATA #REQUIRED
	force_vendor CDATA #REQUIRED
>
<!ELEMENT inferred (#PCDATA)*>
<!ATTLIST inferred
	scale CDATA #REQUIRED
>
<!ELEMENT opencl (#PCDATA)*>
<!ATTLIST opencl
	platform CDATA #REQUIRED
	clear_cache CDATA #REQUIRED
>
<!ELEMENT albion (#PCDATA | map | debug)*>
<!ELEMENT map (#PCDATA)*>
<!ATTLIST map
	scale_2d CDATA #REQUIRED
	scale_3d CDATA #REQUIRED
	object_lights CDATA #REQUIRED
	collision CDATA #REQUIRED
	hour CDATA #REQUIRED
>
<!ELEMENT debug (#PCDATA)*>
<!ATTLIST debug
	free_cam CDATA #REQUIRED
	player_gfx CDATA #REQUIRED
>

=== cvogt/freealbion/data/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE config PUBLIC "-//A2E//DTD config 1.0//EN" "config.dtd">
<config>
	<!-- screen resolution and fullscreen/vsync settings (stereo serves no purpose right now) -->
	<screen width="1280" height="720" fullscreen="0" vsync="0" stereo="0"/>
	<!--<screen width="1920" height="1080" fullscreen="1" vsync="1" stereo="0"/>-->

	<!--
	 dpi: use this to overwrite the auto-detected dpi value (0: use auto-detect)
	 anti_aliasing options: 0 - max MSAA value allowed by graphics card (8 is recommended)
	-->
	<gui dpi="0" anti_aliasing="2"/>

	<!-- you might want to change the field of view, but near/far should remain at 1/1000 -->
	<projection fov="72.0" near="0.1" far="1000.0"/>

	<!-- there should be no need to change these -->
	<input key_repeat="0" ldouble_click="10" mdouble_click="10" rdouble_click="10"/>

	<!-- this will sleep the program for the specified amount of milliseconds after each rendered frame -->
	<sleep time="0"/>

	<!--
	 filtering options: POINT, LINEAR, BILINEAR, TRILINEAR
	 anisotropic options: 0 (disabled), 1 - 16
	 anti_aliasing options: NONE, FXAA, 2xSSAA, 4/3xSSAA+FXAA, 2xSSAA+FXAA (others are currently unsupported)
	-->
	<graphic filtering="TRILINEAR" anisotropic="16" anti_aliasing="FXAA"/>

	<!--
	 upscaling: sets the upscaling factor
		e.g. a value of 2.0 with screen width/height set to 1280*720 will lead to rendering at 640*360 and then scaling it back up to 1280*720
	 geometry_light_scaling: sets the additional scaling of the geometry and light buffer (note: it is not recommended to change this value!)
		valid values are: 0.5, 0.625, 0.75, 0.875, 1.0 (anything above 1.0 has no effect, anything below 0.5 will lead to broken rendering)
	-->
	<inferred upscaling="2.0" geometry_light_scaling="1.0"/>

	<!-- unless you know what you're doing, don't change the following settings
	 opencl platform options: either the opencl platform index (starting by 0) or "cuda" on supported platforms (OS X and Linux only)
	 opencl restrict options: if this is set to any of (or a list of) "CPU", "GPU" or "ACCELERATOR", only those kind/type of devices are used
	-->
	<graphic_device disabled_extensions="" force_device="" force_vendor=""/>
	<opencl platform="0" clear_cache="1" restrict=""/>

	<!-- misc albion settings (you may change these) -->
	<albion>
		<!--
		 scale_2d: don't change this!
		 scale_3d options: 1x, 2x, 4x, hq2x, hq4x
		 note: this mostly influences the load time, not so much the rendering performance (if you have enough VRAM), hq4x is recommended
		 object_lights: 0 (on) or 1 (off), if enabled, this will add a light source for each "light map object" (lamps/etc.)
		 collision: 0 (on) or 1 (off)
		 hour: the hour in which the game should start (0 - 23, obviously)
		-->
		<map scale_2d="hq4x" scale_3d="hq4x" object_lights="1" collision="1" hour="8"/>
		
		<!--
		 free_cam: 0 or 1 (1 doesn't pin the player to the ground and disables collision detection)
		 player_gfx: sets the 2d player gfx, e.g. 200 = Tom, 167 = AI (range: 0 - 209, this also contains invalid values!)
		-->
		<debug free_cam="1" player_gfx="200"/>
	</albion>
</config>
